from django.db import models

class Event(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateField()
    location = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} on {self.date}"

class VideoAsset(models.Model):
    STATUS_CHOICES = (
        ('PENDING', 'Pending'),
        ('PROCESSING', 'Processing'),
        ('COMPLETED', 'Completed'),
        ('FAILED', 'Failed'),
    )

    event = models.ForeignKey(Event, related_name='videos', on_delete=models.CASCADE)
    file_path = models.FileField(upload_to='videos/')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    progress_percent = models.IntegerField(default=0)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Video for {self.event.name} ({self.status})"

class CrowdAnalytics(models.Model):
    video_asset = models.OneToOneField(VideoAsset, related_name='analytics', on_delete=models.CASCADE)
    timeline_data = models.JSONField(help_text="Time-stamped JSON payload generated by offline_processor.py")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Analytics for {self.video_asset}"
