# Generated by Django 6.1 on 2026-08-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoasset",
            name="progress_percent",
            field=models.IntegerField(default=0),
        ),
    ]
